apiVersion: v1
kind: Service
metadata:
  name: devpassport-prod-nodeport
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: devpassport-prod
  ports:
  - protocol: TCP
    port: 60000
    targetPort: 3000
    nodePort: 32687