apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpassport-insert-service
  labels:
    app: devpassport-insert-service
    pvm: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devpassport-insert-service
  template:
    metadata:
      labels:
        app: devpassport-insert-service
    spec:
      containers:
      - name: devpassport-insert-service
        image: gcr.io/devpassport-228701/github.com/scottefein/devpassport-insert-service:latest
        imagePullPolicy: Always
        env:
          - name: ENCODED_GOOGLE_APPLICATION_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: ENCODED_GOOGLE_APPLICATION_CREDENTIALS
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: devsecrets
                key: DB_PORT
      priorityClassName: low-priority

        